export const USING_ADDITION = "use"
export const RECORD_ADDITION = "record"
export const ASSESSMENT_ADDITION = "assessment"
export const TRAINING_ADDITION = "training"
export const TREATMENT_ADDITION = "treatment"
export const HARVEST_ADDITION = "harvest"