import StyledComponentsRegistry from '@/lib/AntdRegistry';
import { ReduxProvider } from '@/redux/provider';
import classNames from 'classnames/bind';
import styles from './page.module.scss';
const cx = classNames.bind(styles);
import type { Metadata } from 'next';
import Providers from '@/components/Provider/Provider';
import { Suspense } from 'react';
import LoadingAll from './loading';

export const metadata: Metadata = {
  title: 'AgriFarm',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={cx('body')}
        suppressHydrationWarning={true}
      >
        <ReduxProvider>
          <StyledComponentsRegistry>
            <Providers>
              <Suspense fallback={<LoadingAll />}>
                <main>{children}</main>
              </Suspense>
            </Providers>
          </StyledComponentsRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
