import StyledComponentsRegistry from '@/lib/AntdRegistry';
import { ReduxProvider } from '@/redux/provider';



import Providers from '@/components/Provider/Provider';

import { roboto } from '@/styles/base/font';
import '../styles/global.scss';
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'AgriFarm',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang='en'
      className={`${roboto.variable}`}
    >
      <ReduxProvider>
        <StyledComponentsRegistry>
          <Providers>
            <body suppressHydrationWarning={false}>
              <main>{children}</main>
            </body>
          </Providers>
        </StyledComponentsRegistry>
      </ReduxProvider>
    </html>
  );
}
